version: '2'

services: 
  download:
    image: xtdockerhub.com/baseimage/xt_releasedownload:20180625
    build: .
    container_name: xt_releasedownload
    ports:
      - 80:80
    volumes:
      - /home/Release:/usr/share/nginx/html/data